# version 1.3

diff --git a/desktop-termux/termux-desktop b/desktop-termux/termux-desktop
--- a/desktop-termux/termux-desktop
+++ b/desktop-termux/termux-desktop
@@ -1,5 +1,10 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
+# check shell
+if ! [ -f /data/data/com.termux/files/usr/bin/bash ];then
+	echo "! unknown termux shell"; exit
+fi
+
 # check repo
 if ! [ -f /data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list ];then
   apt install x11-repo -y
@@ -96,9 +101,11 @@ run_desktop(){
     #echo "false"
     vncserver -xstartup $PREFIX/bin/xfce4-session; pulseaudio --start --exit-idle-time=-1
   fi
+  
   # intent to vnc viewer android
-  if [ -d /data/user/0/com.realvnc.viewer.android ];then
-    am start --user 0 -n com.realvnc.viewer.android/com.realvnc.viewer.android.app.ConnectionChooserActivity
+  if [ -f $PREFIX/etc/vnc.app.activity ];then
+    activity=$(cat $PREFIX/etc/vnc.app.activity)
+    am start --user 0 -n $activity
   fi
   clear
 }
@@ -107,9 +114,11 @@ run_desktop(){
 run_help(){
   echo "termux-desktop [option] [command]"
   echo "Options :"
-  echo -e "-s\t\t: set prosess"
+  echo -e "-k\t\t: kill proses"
+  echo -e "-s\t\t: set proses"
   echo -e "-c\t\t: check proses\n"
   echo "Command :"
+  echo -e "activity\t: open activity app vnc viewer"
   echo -e "run_always\t: proses otomatis mulai desktop"
   echo -e "layer\t\t: ukuran layar hp"
   echo -e "desktop\t\t: proses vnc sedang berjalan\n"
@@ -123,10 +132,18 @@ if [[ $1 == "-c" ]];then
     vncserver -list
   # check size layer
   elif [[ $2 == "layer" ]] && [ -z $3 ];then
-    if ! [ -f $PREFIX/etc/vnc.layer ];then
+    if [ -f $PREFIX/etc/vnc.layer ];then
+      cat $PREFIX/etc/vnc.layer
+    else
       echo "[!] file <$PREFIX/etc/vnc.layer> not found"; exit
     fi
-    cat $PREFIX/etc/vnc.layer
+  elif [[ $2 == "activity" ]] && [ -z $3 ];then
+    # check activity
+    if [ -f $PREFIX/etc/vnc.app.activity ];then
+      cat $PREFIX/etc/vnc.app.activity
+    else
+      echo "[!] file <$PREFIX/etc/vnc.app.activity> not found"; exit
+    fi
   # check otomatis running
   elif [[ $2 == "run_always" ]] && [ -z $3 ];then
     c_fprofile $0 2
@@ -161,8 +178,30 @@ elif [[ $1 == "-s" ]];then
       echo "[!] command <$3> unknown"
       echo "[?] example : 1200x720"
     fi
+  elif [[ $2 == "activity" ]] && [ $3 ] && [ -z $4 ];then
+    # set activity
+    if [ -f $PREFIX/etc/vnc.app.activity ];then
+      cd $PREFIX/etc; rm vnc.app.activity
+    else
+	  touch $PREFIX/etc/vnc.app.activity
+	  echo $3 >> $PREFIX/etc/vnc.app.activity
+	  echo "[!] set app vnc activity success"
+    fi
   else
     run_help
+  fi
+elif [[ $1 == "-k" ]] || [[ $1 == "-kill" ]] && [ -z $2 ];then
+  cd /data/data/com.termux/files/usr
+  # kill desktop
+  for p in {1..10};do
+	if [ -f tmp/.X$p-lock ];then
+		vncserver -kill :$p
+	fi
+  done
+  # clear cache vnc
+  if [ -d tmp ];then
+  	rm -rf tmp/*
+  	rm -rf tmp/.*
   fi
 elif [[ $1 == "-h" ]] || [[ $1 == "--help" ]] && [ -z $2 ];then
   run_help
@@ -170,25 +209,11 @@ else
   # check desktop install
   c_install
 
-  # get display desktop
-  gdisplay=( $(vncserver -list) )
-
-  # check desktop already running
-  for c_dbus in $(ls $PREFIX/tmp);do
-    #echo $c_dbus
-    get_char_dbus=${c_dbus:0:4}
-    #echo $get_char_dbus
-    if [[ $get_char_dbus == "dbus" ]];then
-      # check list display
-      if [ -f $PREFIX/tmp/.X2-lock ] || [[ ${gdisplay[8]} != ":1" ]];then
-        rm -rf $PREFIX/tmp/.*
-        rm -rf $PREFIX/tmp/*
-        echo "[!] restart termux for repair"
-      fi
-      exit
-    fi
-  done
-
+  # check run desktop
+  if [ -f /data/data/com.termux/files/usr/tmp/.X1-lock ];then
+	exit
+  fi
+  
   # run check file vnc.layer
   if [ -f $PREFIX/etc/vnc.layer ];then
     u_layer="$(cat $PREFIX/etc/vnc.layer)"
@@ -196,6 +221,7 @@ else
   else
     run_desktop
   fi
+  
 fi
 
 # try method
